// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: naukleros/retriever.proto

package naukleros

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event and tracking data for relevance check.
type ShouldFetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Before        string                 `protobuf:"bytes,3,opt,name=before,proto3" json:"before,omitempty"`
	After         string                 `protobuf:"bytes,4,opt,name=after,proto3" json:"after,omitempty"`
	TrackedRef    string                 `protobuf:"bytes,5,opt,name=tracked_ref,json=trackedRef,proto3" json:"tracked_ref,omitempty"`
	TrackedPath   string                 `protobuf:"bytes,6,opt,name=tracked_path,json=trackedPath,proto3" json:"tracked_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShouldFetchRequest) Reset() {
	*x = ShouldFetchRequest{}
	mi := &file_naukleros_retriever_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShouldFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShouldFetchRequest) ProtoMessage() {}

func (x *ShouldFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShouldFetchRequest.ProtoReflect.Descriptor instead.
func (*ShouldFetchRequest) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{0}
}

func (x *ShouldFetchRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *ShouldFetchRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ShouldFetchRequest) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *ShouldFetchRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *ShouldFetchRequest) GetTrackedRef() string {
	if x != nil {
		return x.TrackedRef
	}
	return ""
}

func (x *ShouldFetchRequest) GetTrackedPath() string {
	if x != nil {
		return x.TrackedPath
	}
	return ""
}

type ShouldFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShouldFetch   bool                   `protobuf:"varint,1,opt,name=should_fetch,json=shouldFetch,proto3" json:"should_fetch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShouldFetchResponse) Reset() {
	*x = ShouldFetchResponse{}
	mi := &file_naukleros_retriever_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShouldFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShouldFetchResponse) ProtoMessage() {}

func (x *ShouldFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShouldFetchResponse.ProtoReflect.Descriptor instead.
func (*ShouldFetchResponse) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{1}
}

func (x *ShouldFetchResponse) GetShouldFetch() bool {
	if x != nil {
		return x.ShouldFetch
	}
	return false
}

// GitOpsIdentity identifies a source to fetch.
type GitOpsIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitOpsIdentity) Reset() {
	*x = GitOpsIdentity{}
	mi := &file_naukleros_retriever_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitOpsIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitOpsIdentity) ProtoMessage() {}

func (x *GitOpsIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitOpsIdentity.ProtoReflect.Descriptor instead.
func (*GitOpsIdentity) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{2}
}

func (x *GitOpsIdentity) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *GitOpsIdentity) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GitOpsIdentity) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GitHubAppCredential struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          int64                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	InstallationId int64                  `protobuf:"varint,2,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	PrivateKey     string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GitHubAppCredential) Reset() {
	*x = GitHubAppCredential{}
	mi := &file_naukleros_retriever_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubAppCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubAppCredential) ProtoMessage() {}

func (x *GitHubAppCredential) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubAppCredential.ProtoReflect.Descriptor instead.
func (*GitHubAppCredential) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{3}
}

func (x *GitHubAppCredential) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GitHubAppCredential) GetInstallationId() int64 {
	if x != nil {
		return x.InstallationId
	}
	return 0
}

func (x *GitHubAppCredential) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type BasicAuthCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicAuthCredential) Reset() {
	*x = BasicAuthCredential{}
	mi := &file_naukleros_retriever_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicAuthCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuthCredential) ProtoMessage() {}

func (x *BasicAuthCredential) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuthCredential.ProtoReflect.Descriptor instead.
func (*BasicAuthCredential) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{4}
}

func (x *BasicAuthCredential) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicAuthCredential) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// RepoCredential holds authentication for accessing a repository.
type RepoCredential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Credential:
	//
	//	*RepoCredential_GithubApp
	//	*RepoCredential_BasicAuth
	Credential    isRepoCredential_Credential `protobuf_oneof:"credential"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoCredential) Reset() {
	*x = RepoCredential{}
	mi := &file_naukleros_retriever_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoCredential) ProtoMessage() {}

func (x *RepoCredential) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoCredential.ProtoReflect.Descriptor instead.
func (*RepoCredential) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{5}
}

func (x *RepoCredential) GetCredential() isRepoCredential_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *RepoCredential) GetGithubApp() *GitHubAppCredential {
	if x != nil {
		if x, ok := x.Credential.(*RepoCredential_GithubApp); ok {
			return x.GithubApp
		}
	}
	return nil
}

func (x *RepoCredential) GetBasicAuth() *BasicAuthCredential {
	if x != nil {
		if x, ok := x.Credential.(*RepoCredential_BasicAuth); ok {
			return x.BasicAuth
		}
	}
	return nil
}

type isRepoCredential_Credential interface {
	isRepoCredential_Credential()
}

type RepoCredential_GithubApp struct {
	GithubApp *GitHubAppCredential `protobuf:"bytes,1,opt,name=github_app,json=githubApp,proto3,oneof"`
}

type RepoCredential_BasicAuth struct {
	BasicAuth *BasicAuthCredential `protobuf:"bytes,2,opt,name=basic_auth,json=basicAuth,proto3,oneof"`
}

func (*RepoCredential_GithubApp) isRepoCredential_Credential() {}

func (*RepoCredential_BasicAuth) isRepoCredential_Credential() {}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *GitOpsIdentity        `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Credential    *RepoCredential        `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_naukleros_retriever_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{6}
}

func (x *FetchRequest) GetIdentity() *GitOpsIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *FetchRequest) GetCredential() *RepoCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

// Streamed source content.
type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_naukleros_retriever_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{7}
}

func (x *FetchResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_naukleros_retriever_proto protoreflect.FileDescriptor

const file_naukleros_retriever_proto_rawDesc = "" +
	"\n" +
	"\x19naukleros/retriever.proto\x12\tnaukleros\"\xb3\x01\n" +
	"\x12ShouldFetchRequest\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x16\n" +
	"\x06before\x18\x03 \x01(\tR\x06before\x12\x14\n" +
	"\x05after\x18\x04 \x01(\tR\x05after\x12\x1f\n" +
	"\vtracked_ref\x18\x05 \x01(\tR\n" +
	"trackedRef\x12!\n" +
	"\ftracked_path\x18\x06 \x01(\tR\vtrackedPath\"8\n" +
	"\x13ShouldFetchResponse\x12!\n" +
	"\fshould_fetch\x18\x01 \x01(\bR\vshouldFetch\"Q\n" +
	"\x0eGitOpsIdentity\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"v\n" +
	"\x13GitHubAppCredential\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x03R\x05appId\x12'\n" +
	"\x0finstallation_id\x18\x02 \x01(\x03R\x0einstallationId\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\"M\n" +
	"\x13BasicAuthCredential\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xa0\x01\n" +
	"\x0eRepoCredential\x12?\n" +
	"\n" +
	"github_app\x18\x01 \x01(\v2\x1e.naukleros.GitHubAppCredentialH\x00R\tgithubApp\x12?\n" +
	"\n" +
	"basic_auth\x18\x02 \x01(\v2\x1e.naukleros.BasicAuthCredentialH\x00R\tbasicAuthB\f\n" +
	"\n" +
	"credential\"\x80\x01\n" +
	"\fFetchRequest\x125\n" +
	"\bidentity\x18\x01 \x01(\v2\x19.naukleros.GitOpsIdentityR\bidentity\x129\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2\x19.naukleros.RepoCredentialR\n" +
	"credential\"#\n" +
	"\rFetchResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\x9e\x01\n" +
	"\x10RetrieverService\x12L\n" +
	"\vShouldFetch\x12\x1d.naukleros.ShouldFetchRequest\x1a\x1e.naukleros.ShouldFetchResponse\x12<\n" +
	"\x05Fetch\x12\x17.naukleros.FetchRequest\x1a\x18.naukleros.FetchResponse0\x01B!Z\x1fgithub.com/katastroma/nauklerosb\x06proto3"

var (
	file_naukleros_retriever_proto_rawDescOnce sync.Once
	file_naukleros_retriever_proto_rawDescData []byte
)

func file_naukleros_retriever_proto_rawDescGZIP() []byte {
	file_naukleros_retriever_proto_rawDescOnce.Do(func() {
		file_naukleros_retriever_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_naukleros_retriever_proto_rawDesc), len(file_naukleros_retriever_proto_rawDesc)))
	})
	return file_naukleros_retriever_proto_rawDescData
}

var file_naukleros_retriever_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_naukleros_retriever_proto_goTypes = []any{
	(*ShouldFetchRequest)(nil),  // 0: naukleros.ShouldFetchRequest
	(*ShouldFetchResponse)(nil), // 1: naukleros.ShouldFetchResponse
	(*GitOpsIdentity)(nil),      // 2: naukleros.GitOpsIdentity
	(*GitHubAppCredential)(nil), // 3: naukleros.GitHubAppCredential
	(*BasicAuthCredential)(nil), // 4: naukleros.BasicAuthCredential
	(*RepoCredential)(nil),      // 5: naukleros.RepoCredential
	(*FetchRequest)(nil),        // 6: naukleros.FetchRequest
	(*FetchResponse)(nil),       // 7: naukleros.FetchResponse
}
var file_naukleros_retriever_proto_depIdxs = []int32{
	3, // 0: naukleros.RepoCredential.github_app:type_name -> naukleros.GitHubAppCredential
	4, // 1: naukleros.RepoCredential.basic_auth:type_name -> naukleros.BasicAuthCredential
	2, // 2: naukleros.FetchRequest.identity:type_name -> naukleros.GitOpsIdentity
	5, // 3: naukleros.FetchRequest.credential:type_name -> naukleros.RepoCredential
	0, // 4: naukleros.RetrieverService.ShouldFetch:input_type -> naukleros.ShouldFetchRequest
	6, // 5: naukleros.RetrieverService.Fetch:input_type -> naukleros.FetchRequest
	1, // 6: naukleros.RetrieverService.ShouldFetch:output_type -> naukleros.ShouldFetchResponse
	7, // 7: naukleros.RetrieverService.Fetch:output_type -> naukleros.FetchResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_naukleros_retriever_proto_init() }
func file_naukleros_retriever_proto_init() {
	if File_naukleros_retriever_proto != nil {
		return
	}
	file_naukleros_retriever_proto_msgTypes[5].OneofWrappers = []any{
		(*RepoCredential_GithubApp)(nil),
		(*RepoCredential_BasicAuth)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_naukleros_retriever_proto_rawDesc), len(file_naukleros_retriever_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_naukleros_retriever_proto_goTypes,
		DependencyIndexes: file_naukleros_retriever_proto_depIdxs,
		MessageInfos:      file_naukleros_retriever_proto_msgTypes,
	}.Build()
	File_naukleros_retriever_proto = out.File
	file_naukleros_retriever_proto_goTypes = nil
	file_naukleros_retriever_proto_depIdxs = nil
}
