// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: naukleros/retriever.proto

package naukleros

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GitHubEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Before        string                 `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After         string                 `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubEvent) Reset() {
	*x = GitHubEvent{}
	mi := &file_naukleros_retriever_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubEvent) ProtoMessage() {}

func (x *GitHubEvent) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubEvent.ProtoReflect.Descriptor instead.
func (*GitHubEvent) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{0}
}

func (x *GitHubEvent) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GitHubEvent) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *GitHubEvent) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

type S3Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketUrl     string                 `protobuf:"bytes,1,opt,name=bucket_url,json=bucketUrl,proto3" json:"bucket_url,omitempty"`
	BucketName    string                 `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3Event) Reset() {
	*x = S3Event{}
	mi := &file_naukleros_retriever_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Event) ProtoMessage() {}

func (x *S3Event) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Event.ProtoReflect.Descriptor instead.
func (*S3Event) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{1}
}

func (x *S3Event) GetBucketUrl() string {
	if x != nil {
		return x.BucketUrl
	}
	return ""
}

func (x *S3Event) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *S3Event) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type OCIEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegistryUrl   string                 `protobuf:"bytes,1,opt,name=registry_url,json=registryUrl,proto3" json:"registry_url,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCIEvent) Reset() {
	*x = OCIEvent{}
	mi := &file_naukleros_retriever_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCIEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCIEvent) ProtoMessage() {}

func (x *OCIEvent) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCIEvent.ProtoReflect.Descriptor instead.
func (*OCIEvent) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{2}
}

func (x *OCIEvent) GetRegistryUrl() string {
	if x != nil {
		return x.RegistryUrl
	}
	return ""
}

func (x *OCIEvent) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *OCIEvent) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type FilesystemEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemEvent) Reset() {
	*x = FilesystemEvent{}
	mi := &file_naukleros_retriever_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemEvent) ProtoMessage() {}

func (x *FilesystemEvent) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemEvent.ProtoReflect.Descriptor instead.
func (*FilesystemEvent) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{3}
}

func (x *FilesystemEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SourceEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SourceEvent_Git
	//	*SourceEvent_S3
	//	*SourceEvent_Oci
	//	*SourceEvent_Fs
	Event         isSourceEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceEvent) Reset() {
	*x = SourceEvent{}
	mi := &file_naukleros_retriever_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceEvent) ProtoMessage() {}

func (x *SourceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceEvent.ProtoReflect.Descriptor instead.
func (*SourceEvent) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{4}
}

func (x *SourceEvent) GetEvent() isSourceEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SourceEvent) GetGit() *GitHubEvent {
	if x != nil {
		if x, ok := x.Event.(*SourceEvent_Git); ok {
			return x.Git
		}
	}
	return nil
}

func (x *SourceEvent) GetS3() *S3Event {
	if x != nil {
		if x, ok := x.Event.(*SourceEvent_S3); ok {
			return x.S3
		}
	}
	return nil
}

func (x *SourceEvent) GetOci() *OCIEvent {
	if x != nil {
		if x, ok := x.Event.(*SourceEvent_Oci); ok {
			return x.Oci
		}
	}
	return nil
}

func (x *SourceEvent) GetFs() *FilesystemEvent {
	if x != nil {
		if x, ok := x.Event.(*SourceEvent_Fs); ok {
			return x.Fs
		}
	}
	return nil
}

type isSourceEvent_Event interface {
	isSourceEvent_Event()
}

type SourceEvent_Git struct {
	Git *GitHubEvent `protobuf:"bytes,2,opt,name=git,proto3,oneof"`
}

type SourceEvent_S3 struct {
	S3 *S3Event `protobuf:"bytes,3,opt,name=s3,proto3,oneof"`
}

type SourceEvent_Oci struct {
	Oci *OCIEvent `protobuf:"bytes,4,opt,name=oci,proto3,oneof"`
}

type SourceEvent_Fs struct {
	Fs *FilesystemEvent `protobuf:"bytes,5,opt,name=fs,proto3,oneof"`
}

func (*SourceEvent_Git) isSourceEvent_Event() {}

func (*SourceEvent_S3) isSourceEvent_Event() {}

func (*SourceEvent_Oci) isSourceEvent_Event() {}

func (*SourceEvent_Fs) isSourceEvent_Event() {}

type GitIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitIdentity) Reset() {
	*x = GitIdentity{}
	mi := &file_naukleros_retriever_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitIdentity) ProtoMessage() {}

func (x *GitIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitIdentity.ProtoReflect.Descriptor instead.
func (*GitIdentity) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{5}
}

func (x *GitIdentity) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *GitIdentity) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GitIdentity) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type S3Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketUrl     string                 `protobuf:"bytes,1,opt,name=bucket_url,json=bucketUrl,proto3" json:"bucket_url,omitempty"`
	BucketName    string                 `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3Identity) Reset() {
	*x = S3Identity{}
	mi := &file_naukleros_retriever_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Identity) ProtoMessage() {}

func (x *S3Identity) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Identity.ProtoReflect.Descriptor instead.
func (*S3Identity) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{6}
}

func (x *S3Identity) GetBucketUrl() string {
	if x != nil {
		return x.BucketUrl
	}
	return ""
}

func (x *S3Identity) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *S3Identity) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type OCIIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegistryUrl   string                 `protobuf:"bytes,1,opt,name=registry_url,json=registryUrl,proto3" json:"registry_url,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCIIdentity) Reset() {
	*x = OCIIdentity{}
	mi := &file_naukleros_retriever_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCIIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCIIdentity) ProtoMessage() {}

func (x *OCIIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCIIdentity.ProtoReflect.Descriptor instead.
func (*OCIIdentity) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{7}
}

func (x *OCIIdentity) GetRegistryUrl() string {
	if x != nil {
		return x.RegistryUrl
	}
	return ""
}

func (x *OCIIdentity) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type FilesystemIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUrl     string                 `protobuf:"bytes,1,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	Folder        string                 `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemIdentity) Reset() {
	*x = FilesystemIdentity{}
	mi := &file_naukleros_retriever_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemIdentity) ProtoMessage() {}

func (x *FilesystemIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemIdentity.ProtoReflect.Descriptor instead.
func (*FilesystemIdentity) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{8}
}

func (x *FilesystemIdentity) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *FilesystemIdentity) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type SourceIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identity:
	//
	//	*SourceIdentity_Git
	//	*SourceIdentity_S3
	//	*SourceIdentity_Oci
	//	*SourceIdentity_Fs
	Identity      isSourceIdentity_Identity `protobuf_oneof:"identity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceIdentity) Reset() {
	*x = SourceIdentity{}
	mi := &file_naukleros_retriever_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceIdentity) ProtoMessage() {}

func (x *SourceIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_naukleros_retriever_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceIdentity.ProtoReflect.Descriptor instead.
func (*SourceIdentity) Descriptor() ([]byte, []int) {
	return file_naukleros_retriever_proto_rawDescGZIP(), []int{9}
}

func (x *SourceIdentity) GetIdentity() isSourceIdentity_Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *SourceIdentity) GetGit() *GitIdentity {
	if x != nil {
		if x, ok := x.Identity.(*SourceIdentity_Git); ok {
			return x.Git
		}
	}
	return nil
}

func (x *SourceIdentity) GetS3() *S3Identity {
	if x != nil {
		if x, ok := x.Identity.(*SourceIdentity_S3); ok {
			return x.S3
		}
	}
	return nil
}

func (x *SourceIdentity) GetOci() *OCIIdentity {
	if x != nil {
		if x, ok := x.Identity.(*SourceIdentity_Oci); ok {
			return x.Oci
		}
	}
	return nil
}

func (x *SourceIdentity) GetFs() *FilesystemIdentity {
	if x != nil {
		if x, ok := x.Identity.(*SourceIdentity_Fs); ok {
			return x.Fs
		}
	}
	return nil
}

type isSourceIdentity_Identity interface {
	isSourceIdentity_Identity()
}

type SourceIdentity_Git struct {
	Git *GitIdentity `protobuf:"bytes,2,opt,name=git,proto3,oneof"`
}

type SourceIdentity_S3 struct {
	S3 *S3Identity `protobuf:"bytes,3,opt,name=s3,proto3,oneof"`
}

type SourceIdentity_Oci struct {
	Oci *OCIIdentity `protobuf:"bytes,4,opt,name=oci,proto3,oneof"`
}

type SourceIdentity_Fs struct {
	Fs *FilesystemIdentity `protobuf:"bytes,5,opt,name=fs,proto3,oneof"`
}

func (*SourceIdentity_Git) isSourceIdentity_Identity() {}

func (*SourceIdentity_S3) isSourceIdentity_Identity() {}

func (*SourceIdentity_Oci) isSourceIdentity_Identity() {}

func (*SourceIdentity_Fs) isSourceIdentity_Identity() {}

var File_naukleros_retriever_proto protoreflect.FileDescriptor

const file_naukleros_retriever_proto_rawDesc = "" +
	"\n" +
	"\x19naukleros/retriever.proto\x12\tnaukleros\"M\n" +
	"\vGitHubEvent\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x16\n" +
	"\x06before\x18\x02 \x01(\tR\x06before\x12\x14\n" +
	"\x05after\x18\x03 \x01(\tR\x05after\"h\n" +
	"\aS3Event\x12\x1d\n" +
	"\n" +
	"bucket_url\x18\x01 \x01(\tR\tbucketUrl\x12\x1f\n" +
	"\vbucket_name\x18\x02 \x01(\tR\n" +
	"bucketName\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\"S\n" +
	"\bOCIEvent\x12!\n" +
	"\fregistry_url\x18\x01 \x01(\tR\vregistryUrl\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\"%\n" +
	"\x0fFilesystemEvent\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xbf\x01\n" +
	"\vSourceEvent\x12*\n" +
	"\x03git\x18\x02 \x01(\v2\x16.naukleros.GitHubEventH\x00R\x03git\x12$\n" +
	"\x02s3\x18\x03 \x01(\v2\x12.naukleros.S3EventH\x00R\x02s3\x12'\n" +
	"\x03oci\x18\x04 \x01(\v2\x13.naukleros.OCIEventH\x00R\x03oci\x12,\n" +
	"\x02fs\x18\x05 \x01(\v2\x1a.naukleros.FilesystemEventH\x00R\x02fsB\a\n" +
	"\x05event\"N\n" +
	"\vGitIdentity\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"d\n" +
	"\n" +
	"S3Identity\x12\x1d\n" +
	"\n" +
	"bucket_url\x18\x01 \x01(\tR\tbucketUrl\x12\x1f\n" +
	"\vbucket_name\x18\x02 \x01(\tR\n" +
	"bucketName\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\"D\n" +
	"\vOCIIdentity\x12!\n" +
	"\fregistry_url\x18\x01 \x01(\tR\vregistryUrl\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"K\n" +
	"\x12FilesystemIdentity\x12\x1d\n" +
	"\n" +
	"server_url\x18\x01 \x01(\tR\tserverUrl\x12\x16\n" +
	"\x06folder\x18\x02 \x01(\tR\x06folder\"\xce\x01\n" +
	"\x0eSourceIdentity\x12*\n" +
	"\x03git\x18\x02 \x01(\v2\x16.naukleros.GitIdentityH\x00R\x03git\x12'\n" +
	"\x02s3\x18\x03 \x01(\v2\x15.naukleros.S3IdentityH\x00R\x02s3\x12*\n" +
	"\x03oci\x18\x04 \x01(\v2\x16.naukleros.OCIIdentityH\x00R\x03oci\x12/\n" +
	"\x02fs\x18\x05 \x01(\v2\x1d.naukleros.FilesystemIdentityH\x00R\x02fsB\n" +
	"\n" +
	"\bidentityB!Z\x1fgithub.com/katastroma/nauklerosb\x06proto3"

var (
	file_naukleros_retriever_proto_rawDescOnce sync.Once
	file_naukleros_retriever_proto_rawDescData []byte
)

func file_naukleros_retriever_proto_rawDescGZIP() []byte {
	file_naukleros_retriever_proto_rawDescOnce.Do(func() {
		file_naukleros_retriever_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_naukleros_retriever_proto_rawDesc), len(file_naukleros_retriever_proto_rawDesc)))
	})
	return file_naukleros_retriever_proto_rawDescData
}

var file_naukleros_retriever_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_naukleros_retriever_proto_goTypes = []any{
	(*GitHubEvent)(nil),        // 0: naukleros.GitHubEvent
	(*S3Event)(nil),            // 1: naukleros.S3Event
	(*OCIEvent)(nil),           // 2: naukleros.OCIEvent
	(*FilesystemEvent)(nil),    // 3: naukleros.FilesystemEvent
	(*SourceEvent)(nil),        // 4: naukleros.SourceEvent
	(*GitIdentity)(nil),        // 5: naukleros.GitIdentity
	(*S3Identity)(nil),         // 6: naukleros.S3Identity
	(*OCIIdentity)(nil),        // 7: naukleros.OCIIdentity
	(*FilesystemIdentity)(nil), // 8: naukleros.FilesystemIdentity
	(*SourceIdentity)(nil),     // 9: naukleros.SourceIdentity
}
var file_naukleros_retriever_proto_depIdxs = []int32{
	0, // 0: naukleros.SourceEvent.git:type_name -> naukleros.GitHubEvent
	1, // 1: naukleros.SourceEvent.s3:type_name -> naukleros.S3Event
	2, // 2: naukleros.SourceEvent.oci:type_name -> naukleros.OCIEvent
	3, // 3: naukleros.SourceEvent.fs:type_name -> naukleros.FilesystemEvent
	5, // 4: naukleros.SourceIdentity.git:type_name -> naukleros.GitIdentity
	6, // 5: naukleros.SourceIdentity.s3:type_name -> naukleros.S3Identity
	7, // 6: naukleros.SourceIdentity.oci:type_name -> naukleros.OCIIdentity
	8, // 7: naukleros.SourceIdentity.fs:type_name -> naukleros.FilesystemIdentity
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_naukleros_retriever_proto_init() }
func file_naukleros_retriever_proto_init() {
	if File_naukleros_retriever_proto != nil {
		return
	}
	file_naukleros_retriever_proto_msgTypes[4].OneofWrappers = []any{
		(*SourceEvent_Git)(nil),
		(*SourceEvent_S3)(nil),
		(*SourceEvent_Oci)(nil),
		(*SourceEvent_Fs)(nil),
	}
	file_naukleros_retriever_proto_msgTypes[9].OneofWrappers = []any{
		(*SourceIdentity_Git)(nil),
		(*SourceIdentity_S3)(nil),
		(*SourceIdentity_Oci)(nil),
		(*SourceIdentity_Fs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_naukleros_retriever_proto_rawDesc), len(file_naukleros_retriever_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_naukleros_retriever_proto_goTypes,
		DependencyIndexes: file_naukleros_retriever_proto_depIdxs,
		MessageInfos:      file_naukleros_retriever_proto_msgTypes,
	}.Build()
	File_naukleros_retriever_proto = out.File
	file_naukleros_retriever_proto_goTypes = nil
	file_naukleros_retriever_proto_depIdxs = nil
}
