// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: naukleros/retriever.proto

package naukleros

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RetrieverService_ShouldFetch_FullMethodName = "/naukleros.RetrieverService/ShouldFetch"
	RetrieverService_Fetch_FullMethodName       = "/naukleros.RetrieverService/Fetch"
)

// RetrieverServiceClient is the client API for RetrieverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RetrieverService fetches source content and determines fetch relevance.
type RetrieverServiceClient interface {
	// ShouldFetch determines if a webhook event requires a pipeline run given
	// the tenant's tracking configuration.
	ShouldFetch(ctx context.Context, in *ShouldFetchRequest, opts ...grpc.CallOption) (*ShouldFetchResponse, error)
	// Fetch retrieves source content from a repository.
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchResponse], error)
}

type retrieverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRetrieverServiceClient(cc grpc.ClientConnInterface) RetrieverServiceClient {
	return &retrieverServiceClient{cc}
}

func (c *retrieverServiceClient) ShouldFetch(ctx context.Context, in *ShouldFetchRequest, opts ...grpc.CallOption) (*ShouldFetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShouldFetchResponse)
	err := c.cc.Invoke(ctx, RetrieverService_ShouldFetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrieverServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RetrieverService_ServiceDesc.Streams[0], RetrieverService_Fetch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchRequest, FetchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RetrieverService_FetchClient = grpc.ServerStreamingClient[FetchResponse]

// RetrieverServiceServer is the server API for RetrieverService service.
// All implementations must embed UnimplementedRetrieverServiceServer
// for forward compatibility.
//
// RetrieverService fetches source content and determines fetch relevance.
type RetrieverServiceServer interface {
	// ShouldFetch determines if a webhook event requires a pipeline run given
	// the tenant's tracking configuration.
	ShouldFetch(context.Context, *ShouldFetchRequest) (*ShouldFetchResponse, error)
	// Fetch retrieves source content from a repository.
	Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchResponse]) error
	mustEmbedUnimplementedRetrieverServiceServer()
}

// UnimplementedRetrieverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRetrieverServiceServer struct{}

func (UnimplementedRetrieverServiceServer) ShouldFetch(context.Context, *ShouldFetchRequest) (*ShouldFetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShouldFetch not implemented")
}
func (UnimplementedRetrieverServiceServer) Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchResponse]) error {
	return status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedRetrieverServiceServer) mustEmbedUnimplementedRetrieverServiceServer() {}
func (UnimplementedRetrieverServiceServer) testEmbeddedByValue()                          {}

// UnsafeRetrieverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RetrieverServiceServer will
// result in compilation errors.
type UnsafeRetrieverServiceServer interface {
	mustEmbedUnimplementedRetrieverServiceServer()
}

func RegisterRetrieverServiceServer(s grpc.ServiceRegistrar, srv RetrieverServiceServer) {
	// If the following call panics, it indicates UnimplementedRetrieverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RetrieverService_ServiceDesc, srv)
}

func _RetrieverService_ShouldFetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShouldFetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieverServiceServer).ShouldFetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrieverService_ShouldFetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieverServiceServer).ShouldFetch(ctx, req.(*ShouldFetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrieverService_Fetch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RetrieverServiceServer).Fetch(m, &grpc.GenericServerStream[FetchRequest, FetchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RetrieverService_FetchServer = grpc.ServerStreamingServer[FetchResponse]

// RetrieverService_ServiceDesc is the grpc.ServiceDesc for RetrieverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RetrieverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "naukleros.RetrieverService",
	HandlerType: (*RetrieverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShouldFetch",
			Handler:    _RetrieverService_ShouldFetch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Fetch",
			Handler:       _RetrieverService_Fetch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "naukleros/retriever.proto",
}
